### PR TITLE
Update syntax of tags for Terraform v0.12.8

### PR DESCRIPTION
**Pull request by taylorgoodallau**
Update syntax of tags in the aws provider for  Terraform v0.12.8

### CODE REVIEW

**Comment by lafraia** [comment]
@giuseppeborgese Latest tag 1.0.1 still uses old syntax

**Comment by giuseppeborgese** [comment]
do you want to push a merge request to fix it?

**Comment by lafraia** [comment]
@giuseppeborgese The master branch is fixed, I believe you just have to push a new version tag.

**Comment by giuseppeborgese** [comment]
@lafraia, you are right, Just added a new tag. Thanks for the suggestion

**Pull request merged**
